name: deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - staging_[a-zA-Z]+[0-9]+

jobs:
  deploy:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
        - uses: actions/checkout@master
        - name: Set up lates Python 3
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Upgrade package tools
          run: >-
            python -m pip install -U
            pip
            setuptools
            wheel
        - name: Build a binary wheel and a source tarball
          run: python setup.py sdist bdist_wheel
        - name: Publish distribution ðŸ“¦ to *Test* PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.TEST_PYPI_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
        - if: startsWith(github.ref, 'refs/tags')
          name: Publish distribution ðŸ“¦ to PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.PYPI_TOKEN }}